### ISSUE TITLE
铁头盔模型问题

### ISSUE THREAD

**Issue by Andepthy** [OEOTYAN/XeKrSquarePattern-BE#1]
![image](https://github.com/OEOTYAN/Squareful-BE/assets/115411501/6bcf5b95-13f1-431d-9b38-31cd29bbc19d)
如图，铁头盔的模型多出了一部分，跟随视角转动，其他头盔可能也存在相同的问题

**Comment by OEOTYAN** [comment]
![image](https://github.com/user-attachments/assets/af73b2a7-ec93-44d6-a3e9-e6b887f8659a)
无法复现
